name = "allenlim-url-worker"
account_id = "9f9fdfcfb6371183304908c2de94513d"
workers_dev = true
compatibility_date = "2026-03-01"

[build]
command = ""

[site]
bucket = "./public"
main = "workers-site/index.js"
